import { Award, BarChart3, Bot, BriefcaseBusiness, Code2, Database, Eye, EyeOff, Gauge, Globe2, GraduationCap, HeartPulse, Microscope, Plus, Rocket, Scale, ShieldCheck, Sparkles, Target, Trash2, TrendingUp, Users } from 'lucide-react'
import { useMemo, useState } from 'react'

const metricIcons = { chart: BarChart3, code: Code2, database: Database, award: Award, users: Users, briefcase: BriefcaseBusiness, bot: Bot, sparkles: Sparkles, trend: TrendingUp, target: Target, gauge: Gauge, health: HeartPulse, research: Microscope, education: GraduationCap, law: Scale, global: Globe2, rocket: Rocket, security: ShieldCheck }
const metricLabels = { chart: 'Gráfico', code: 'Código', database: 'Dados', award: 'Prêmio', users: 'Pessoas', briefcase: 'Trabalho', bot: 'IA', sparkles: 'Destaque', trend: 'Crescimento', target: 'Meta', gauge: 'Desempenho', health: 'Saúde', research: 'Pesquisa', education: 'Educação', law: 'Direito', global: 'Alcance', rocket: 'Lançamento', security: 'Segurança' }
const parseRows = (text, keys) => (text || '').split('\n').filter(Boolean).map((line, index) => Object.fromEntries([['id', `${index}-${line}`], ...line.split('|').map((value, item) => [keys[item], value?.trim() || ''])]))
const serializeRows = (rows, keys) => rows.map((row) => keys.map((key) => row[key] || '').join('|')).join('\n')

export function AdminProfessionalContent({ siteStore, onOpenLibrary }) {
  const metrics = siteStore.site.metrics || []
  const stickers = siteStore.site.stickerLibrary || []
  const [metricId, setMetricId] = useState(metrics[0]?.id || '')
  const selected = metrics.find((item) => item.id === metricId) || metrics[0]
  const timeline = useMemo(() => parseRows(siteStore.site.timelineText, ['period', 'title', 'text']), [siteStore.site.timelineText])
  const testimonials = useMemo(() => parseRows(siteStore.site.testimonialsText, ['name', 'role', 'quote']), [siteStore.site.testimonialsText])
  const saveMetrics = (next) => siteStore.updateSite({ metrics: next })
  const updateMetric = (changes) => selected && saveMetrics(metrics.map((item) => item.id === selected.id ? { ...item, ...changes } : item))
  const addMetric = () => { const id = `metrica-${Date.now()}`; saveMetrics([...metrics, { id, value: '+1', label: 'Nova métrica', icon: 'sparkles', color: '#55b8ff', image: '', visible: true }]); setMetricId(id) }
  const removeMetric = () => { if (!selected || !window.confirm(`Excluir a métrica “${selected.label}”?`)) return; const next = metrics.filter((item) => item.id !== selected.id); saveMetrics(next); setMetricId(next[0]?.id || '') }
  const updateTimeline = (index, changes) => { const next = timeline.map((item, itemIndex) => itemIndex === index ? { ...item, ...changes } : item); siteStore.updateSite({ timelineText: serializeRows(next, ['period', 'title', 'text']) }) }
  const updateTestimonial = (index, changes) => { const next = testimonials.map((item, itemIndex) => itemIndex === index ? { ...item, ...changes } : item); siteStore.updateSite({ testimonialsText: serializeRows(next, ['name', 'role', 'quote']) }) }

  return <div className="admin-professional-content">
    <div className="admin-page__heading"><span>Conteúdo profissional</span><h3>Métricas, trajetória e depoimentos</h3><p>Esta é a área que alimenta os números da abertura e a seção de credibilidade do site.</p></div>

    <section className="professional-editor-section">
      <div className="appearance-section__heading"><span>Indicadores</span><h4>Cards de números e figuras</h4><p>Crie, edite, exclua e escolha ícone ou figurinha. Os três primeiros cards visíveis aparecem também no topo do site.</p></div>
      <div className="professional-editor-layout">
        <aside className="specialty-editor-list"><button type="button" onClick={addMetric}><Plus size={15} /> Nova métrica</button><div>{metrics.map((item) => { const Icon = metricIcons[item.icon] || Sparkles; return <button className={selected?.id === item.id ? 'is-active' : ''} type="button" key={item.id} onClick={() => setMetricId(item.id)}>{item.image ? <img src={item.image} alt="" /> : <Icon size={18} style={{ color: item.color }} />}<span><strong>{item.value}</strong><small>{item.label}</small></span></button> })}</div></aside>
        <div className="specialty-editor-form">{selected ? <><div className="specialty-editor-form__head"><div><span>Métrica editável</span><h4>{selected.label}</h4></div><button type="button" onClick={removeMetric}><Trash2 size={14} /> Excluir</button></div><div className="admin-form"><label className="field">Número ou valor<input value={selected.value} onChange={(event) => updateMetric({ value: event.target.value })} /></label><label className="field">Legenda<input value={selected.label} onChange={(event) => updateMetric({ label: event.target.value })} /></label><label className="field">Cor<input type="color" value={selected.color || '#55b8ff'} onChange={(event) => updateMetric({ color: event.target.value })} /></label><button className={`specialty-visibility-toggle ${selected.visible === false ? 'is-hidden' : ''}`} type="button" onClick={() => updateMetric({ visible: selected.visible === false })}>{selected.visible === false ? <><EyeOff size={16} /> Oculta — mostrar</> : <><Eye size={16} /> Visível — ocultar</>}</button></div><div className="metric-icon-library"><strong>Escolha visualmente um ícone</strong><p>Exemplos para metas, pessoas, relatórios, saúde, pesquisa e tecnologia.</p><div>{Object.entries(metricIcons).map(([key, Icon]) => <button className={!selected.image && selected.icon === key ? 'is-active' : ''} type="button" key={key} title={metricLabels[key]} onClick={() => updateMetric({ icon: key, image: '' })}><Icon size={20} /><span>{metricLabels[key]}</span></button>)}</div></div><div className="specialty-stickers"><strong>Ou use uma figurinha da coleção</strong><div>{stickers.map((sticker) => <button className={selected.image === sticker.image ? 'is-active' : ''} type="button" key={sticker.id} onClick={() => updateMetric({ image: sticker.image })}><img src={sticker.image} alt="" /><span>{sticker.name}</span></button>)}</div><button className="open-sticker-library" type="button" onClick={onOpenLibrary}><Plus size={15} /> Adicionar em Box/figurinhas</button><p className="icon-source-note">Você pode baixar PNG, WebP ou SVG em <a href="https://lucide.dev/icons/" target="_blank" rel="noreferrer">Lucide</a>, <a href="https://fonts.google.com/icons" target="_blank" rel="noreferrer">Google Icons</a>, <a href="https://www.svgrepo.com/" target="_blank" rel="noreferrer">SVG Repo</a> ou <a href="https://www.flaticon.com/" target="_blank" rel="noreferrer">Flaticon</a>. Confira a licença antes de publicar.</p></div></> : <p>Nenhuma métrica cadastrada.</p>}</div>
      </div>
    </section>

    <section className="professional-editor-section"><div className="professional-section-title"><div><span>Trajetória</span><h4>Experiências e marcos profissionais</h4></div><button type="button" onClick={() => siteStore.updateSite({ timelineText: serializeRows([...timeline, { period: 'Período', title: 'Novo marco', text: 'Descrição da experiência.' }], ['period', 'title', 'text']) })}><Plus size={15} /> Adicionar</button></div><div className="repeatable-editor">{timeline.map((item, index) => <article key={`${item.id}-${index}`}><label>Período<input value={item.period} onChange={(event) => updateTimeline(index, { period: event.target.value })} /></label><label>Título<input value={item.title} onChange={(event) => updateTimeline(index, { title: event.target.value })} /></label><label className="wide">Descrição<textarea rows="2" value={item.text} onChange={(event) => updateTimeline(index, { text: event.target.value })} /></label><button type="button" aria-label="Excluir marco" onClick={() => siteStore.updateSite({ timelineText: serializeRows(timeline.filter((_, itemIndex) => itemIndex !== index), ['period', 'title', 'text']) })}><Trash2 size={15} /></button></article>)}</div></section>

    <section className="professional-editor-section"><div className="professional-section-title"><div><span>Depoimentos</span><h4>Recomendações autorizadas</h4></div><button type="button" onClick={() => siteStore.updateSite({ testimonialsText: serializeRows([...testimonials, { name: 'Nome', role: 'Cargo ou empresa', quote: 'Depoimento autorizado.' }], ['name', 'role', 'quote']) })}><Plus size={15} /> Adicionar</button></div><div className="repeatable-editor">{testimonials.map((item, index) => <article key={`${item.id}-${index}`}><label>Nome<input value={item.name} onChange={(event) => updateTestimonial(index, { name: event.target.value })} /></label><label>Cargo ou empresa<input value={item.role} onChange={(event) => updateTestimonial(index, { role: event.target.value })} /></label><label className="wide">Depoimento<textarea rows="2" value={item.quote} onChange={(event) => updateTestimonial(index, { quote: event.target.value })} /></label><button type="button" aria-label="Excluir depoimento" onClick={() => siteStore.updateSite({ testimonialsText: serializeRows(testimonials.filter((_, itemIndex) => itemIndex !== index), ['name', 'role', 'quote']) })}><Trash2 size={15} /></button></article>)}</div></section>
  </div>
}
